# Generated by Django 3.1 on 2020-09-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoolPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRegistry.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoolBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRegistry.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='apiRegistry.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_issue', models.DateField()),
                ('date_expiry', models.DateField()),
                ('issuer', models.CharField(max_length=128)),
                ('identifier', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRegistry.organization')),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRegistry.certificaterule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('date_production_start', models.DateField()),
                ('date_best_before', models.DateField()),
                ('origin_country', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRegistry.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
