# Generated by Django 3.1 on 2021-02-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date_best_before',
            field=models.DateField(blank=True, null=True),
        ),
    ]
