# Generated by Django 3.1.7 on 2021-03-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0002_auto_20210202_1125'),
        ('apiRegistry', '0002_kv'),
    ]

    operations = [
    ]
