# Generated by Django 3.1 on 2021-04-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiRegistry', '0002_auto_20210202_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raddress', models.CharField(editable=False, max_length=34, unique=True)),
                ('pubkey', models.CharField(editable=False, max_length=66, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_wallet', to='apiRegistry.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='poolpurchaseorder',
            name='organization',
        ),
        migrations.DeleteModel(
            name='PoolBatch',
        ),
        migrations.DeleteModel(
            name='PoolPurchaseOrder',
        ),
    ]
